---
- name: Create AutoShift Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ autoshift_data_directory }}/data"

- name: AutoShift Scraper Docker Container
  docker_container:
    name: autoshift-scraper
    image: ghcr.io/dylancyclone/autoshift-scraper:master
    pull: true
    volumes:
      - "{{ autoshift_data_directory }}/data:/autoshift-scraper/data:rw"
    env:
      GITHUB_USER: "na"
      GITHUB_REPO: "na"
      GITHUB_TOKEN: "na"
      PARSER_ARGS: "--verbose --schedule 2"
    restart_policy: unless-stopped
    memory: "{{ autoshift_memory }}"

- name: AutoShift Docker Container
  docker_container:
    name: autoshift
    image: ghcr.io/dylancyclone/autoshift:doco-update
    pull: true
    volumes:
      - "{{ autoshift_data_directory }}/data:/autoshift/data:rw"
    env:
      SHIFT_USER: "{{ autoshift_username }}"
      SHIFT_PASS: "{{ autoshift_password }}"
      SHIFT_GAMES: "{{ autoshift_games }}"
      SHIFT_PLATFORMS: "{{ autoshift_platform }}"
    restart_policy: unless-stopped
    memory: "{{ autoshift_memory }}"
