---
- name: Create AutoShift Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ autoshift_data_directory }}/data"

- name: AutoShift Docker Container
  docker_container:
    name: autoshift
    image: ugoogalizer/autoshift:latest
    pull: true
    volumes:
      - "{{ autoshift_data_directory }}/data:/autoshift/data:rw"
    env:
      SHIFT_USER: "{{ autoshift_username }}"
      SHIFT_PASS: "{{ autoshift_password }}"
      SHIFT_GAMES: "{{ autoshift_games }}"
      SHIFT_PLATFORMS: "{{ autoshift_platform }}"
    restart_policy: unless-stopped
    memory: "{{ autoshift_memory }}"
