---
- name: CyberChef Docker Container
  docker_container:
    name: CyberChef
    image: mpepping/cyberchef:latest
    pull: true
    ports:
      - "{{ cyberchef_port }}:8000"
    restart_policy: unless-stopped
    memory: "{{ cyberchef_memory }}"
    labels:
      traefik.enable: "{{ cyberchef_available_externally }}"
      traefik.http.routers.cyberchef.rule: "Host(`{{ cyberchef_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.cyberchef.tls.certresolver: "letsencrypt"
      traefik.http.routers.cyberchef.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.cyberchef.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.cyberchef.loadbalancer.server.port: "8000"
