---
- name: Start Homepage
  block:
    - name: Create Homepage Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ homepage_data_directory }}"

    - name: Homepage Docker Container
      community.docker.docker_container:
        name: "{{ homepage_container_name }}"
        image: ghcr.io/gethomepage/homepage:latest
        pull: true
        ports:
          - "{{ homepage_port }}:3000"
        restart_policy: unless-stopped
        memory: "{{ homepage_memory }}"
        volumes:
          - "{{ homepage_data_directory }}/:/app/config:rw"
          - "/var/run/docker.sock:/var/run/docker.sock"
        env:
          HOMEPAGE_ALLOWED_HOSTS: "{{ homepage_hostname }}.{{ ansible_nas_domain }}"
        labels:
          traefik.enable: "{{ homepage_available_externally | string }}"
          traefik.http.routers.homepage.rule: "Host(`{{ homepage_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.homepage.tls.certresolver: "letsencrypt"
          traefik.http.routers.homepage.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.homepage.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.homepage.loadbalancer.server.port: "3000"
  when: homepage_enabled

- name: Stop Homepage
  block:
    - name: Stop Homepage
      community.docker.docker_container:
        name: "{{ homepage_container_name }}"
        state: absent
  when: not homepage_enabled
