---
- name: Create Gickup Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ gickup_data_directory }}"
    - "{{ gickup_download_directory }}"

- name: Template Gickup conf.yml
  template:
    src: conf.yml
    dest: "{{ gickup_data_directory }}/conf.yml"
  register: template_config

- name: Gickup
  docker_container:
    name: gickup
    image: buddyspencer/gickup:latest
    pull: true
    volumes:
      - "{{ gickup_download_directory }}:/downloads:rw"
      - "{{ gickup_data_directory }}/conf.yml:/gickup/conf.yml:ro"
    env:
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: "{{ gickup_memory }}"