---
- name: Create memos Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ memos_data_directory }}/config"

- name: Memos Docker Container
  docker_container:
    name: memos
    image: neosmemo/memos:latest
    pull: true
    volumes:
      - "{{ memos_data_directory }}/config:/var/opt/memos:rw"
    ports:
      - "{{ memos_port }}:5230"
    restart_policy: unless-stopped
    memory: "{{ memos_memory }}"
    labels:
      traefik.enable: "{{ memos_available_externally }}"
      traefik.http.routers.memos.rule: "Host(`{{ memos_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.memos.tls.certresolver: "letsencrypt"
      traefik.http.routers.memos.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.memos.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.memos.loadbalancer.server.port: "5230"
