---
homepage_enabled: false
homepage_available_externally: false

# directories
homepage_data_directory: "{{ docker_home }}/homepage"

# network
homepage_port: "8100"
homepage_hostname: "homepage"

# specs
homepage_memory: 1g

# docker
homepage_container_name: homepage
