---
- name: Start Sterling PDF
  block:
    - name: Create Sterling PDF Directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ sterlingpdf_data_directory }}"

    - name: Sterling PDF Docker Container
      docker_container:
        name: "{{ sterlingpdf_container_name }}"
        image: frooodle/s-pdf:latest
        pull: true
        ports:
          - "{{ sterlingpdf_port }}:8080"
        volumes:
          - "{{ sterlingpdf_data_directory }}:/configs:rw"
        env:
          DOCKER_ENABLE_SECURITY: "false"
        restart_policy: unless-stopped
        memory: "{{ sterlingpdf_memory }}"
        labels:
          traefik.enable: "{{ sterlingpdf_available_externally | string }}"
          traefik.http.routers.sterlingpdf.rule: "Host(`{{ sterlingpdf_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.sterlingpdf.tls.certresolver: "letsencrypt"
          traefik.http.routers.sterlingpdf.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.sterlingpdf.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.sterlingpdf.loadbalancer.server.port: "8080"
  when: sterlingpdf_enabled

- name: Stop Sterling PDF
  block:
    - name: Stop Sterling PDF
      docker_container:
        name: "{{ sterlingpdf_container_name }}"
        state: absent
  when: not sterlingpdf_enabled
