[entryPoints]
  [entryPoints.web]
    address = ":{{ traefik_port_http }}"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"

  [entryPoints.websecure]
    address = ":{{ traefik_port_https }}"

      [entryPoints.websecure.http.tls]
        certResolver = "letsencrypt"

        [entryPoints.websecure.http.tls.domains]
          main = "{{ ansible_nas_domain }}"
          sans = [
            "*.{{ ansible_nas_domain }}"
          ]

  [entryPoints.traefik]
    address = ":{{ traefik_port_ui }}"

[tls.stores.default.defaultCertificate]
  certFile = "/etc/traefik/lathrumpubkey.pem"
  keyFile = "/etc/traefik/lathrumprivkey.pem"

[[tls.certificates]]
  certFile = "/etc/traefik/lathrumpubkey.pem"
  keyFile = "/etc/traefik/lathrumprivkey.pem"
  stores = ["default"]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    exposedbydefault = false
  [providers.file]
    filename = "/etc/traefik/tls-certs.toml"
    watch = true  

[api]
  insecure = true
  dashboard = true

[log]
  level = "{{ traefik_log_level }}"

[ping]
  terminatingStatusCode = 0
[metrics]
  [metrics.prometheus]
