---
- name: Start Feishin
  block:
    - name: Feishin Docker Container
      docker_container:
        name: "feishin"
        image: "ghcr.io/jeffvli/feishin:latest"
        pull: true
        ports:
          - "{{ feishin_port }}:9180"
        restart_policy: unless-stopped
        memory: "{{ feishin_memory }}"
        labels:
          traefik.enable: "{{ feishin_available_externally | string }}"
          traefik.http.routers.feishin.rule: "Host(`{{ feishin_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.feishin.tls.certresolver: "letsencrypt"
          traefik.http.routers.feishin.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.feishin.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.feishin.loadbalancer.server.port: "9180"
  when: feishin_enabled

- name: Stop Feishin
  block:
    - name: Stop Feishin
      docker_container:
        name: "feishin"
        state: absent
  when: not feishin_enabled
